### ISSUE TITLE
004_blikani_led.md - úkol 2 - LED se nikdy nerozsvítí. Není jasné zadání.

### ISSUE THREAD

**Issue by MarPta** [RoboticsBrno/robotka.robotickytabor.cz#11]

**Comment by bsaid** [comment]
V úkolu nevidím nic nejasného a LEDka se podle mě rozsvítí. Zadání je toto:
"Začneme funkcí delay. Ta pozastaví běh programu na dobu uvedenou v parametru (závorkách). Hodnota je udávána v milisekundách, neboli tisícinách vteřiny.
Napíšeme si program, který nejprve rozsvítí a následně po půl vteřině zhasne modrou LED."

**Comment by mkousal** [comment]
Upravte tento řádek v kódu tak, aby LED svítila pouze půl vteřiny!
